### ISSUE TITLE
/api/something doesn't work

### ISSUE THREAD

**Issue by gilbertsmink** [TutorFx/nuxtjs-fastapi#6]
Hey nice work here, exactly what I was looking for.

Everything works locally, but in production there is a problem. /api is fine, but /api/something doesn't work. I did add /api/something to fastapi in python. The error is a 404 NOT_FOUND from Vercel. Any ideas?

<img width="524" alt="Screenshot 2024-09-09 at 20 22 36" src="https://github.com/user-attachments/assets/a43c9144-550e-45ef-875c-0b51149de413">

**Comment by TutorFx** [comment]
@gilbertsmink Thank you for your contribution! I'm very happy that this project has helped you in some way. Any other changes or suggestions, I will be very happy to implement. Since Nuxt 3 automatically generates vercel.json, to avoid conflicts, I put the settings for the Python route inside the Nuxt config.
